### PR TITLE
add sepolia & mainnet etherscan env vars

### PR DESCRIPTION
**Pull request by justinkaseman**

### CODE REVIEW

**Review by bolekk — CHANGES_REQUESTED** [review]
Can you remove unrelated formatting changes and also add the link/eth feed address to network-config.js?

  sepolia: {
    linkEthPriceFeed: "0x42585eD362B3f1BCa95c640FdFf35Ef899212734",

**Comment by KuphJr** [comment]
Other than Bolekk's comments LGTM

**Review by KuphJr — APPROVED** [review]

**Comment by justinkaseman** [comment]
> Can you remove unrelated formatting changes and also add the link/eth feed address to network-config.js?
> 
> sepolia: { linkEthPriceFeed: "0x42585eD362B3f1BCa95c640FdFf35Ef899212734",

I'm adding the Sepolia LINK/ETH feed to [this PR](https://github.com/smartcontractkit/functions-hardhat-starter-kit/pull/62)

As for the formatting changes, this is becoming frustrating that this is a re-occuring problem. I am using the repo's local prettier rules here. We can add a CI step that runs prettier format, but in general I shouldn't need to re-do my PR because someone else is not doing things properly.

**Comment by bolekk** [comment]
I understand the frustration but the correct way to do this is send out a separate PR that re-formats everything correctly. Mixing random re-formatting with actual logic changes makes PRs much harder to review. Not a big deal here but let's get those settings right. I've never seen those problems in core repo.

**Review by bolekk — APPROVED** [review]

**Comment by justinkaseman** [comment]
> I've never seen those problems in core repo.
Because core repo has the proper tooling set up to avoid this problem

**Pull request merged**
